config/routes.rb
require 'sidekiq/web'
class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

Edcast::Application.routes.draw do

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post "/graphql", to: "graphql#execute"
  use_doorkeeper do
    # it accepts :authorizations, :tokens, :applications and :authorized_applications
    skip_controllers :applications, :authorized_applications
  end

  ## WEBAPP ENDPOINTS

  devise_for :users, path_prefix: 'auth', controllers: { sessions: "users/sessions", confirmations: 'confirmations', registrations: 'registrations', passwords: 'passwords' }
  apipie

  controller 'user_pages' do
    get 'settings(/:tab)', action: 'settings', as: 'settings'
    get 'notifications'
    get 'channels(/:tab)', action: 'channels', as: :user_channels_page
    put 'edit_settings'
    patch 'handle'
    get '/users/:handle', to: 'user_pages#check_handle', as: 'check_handle'
    # get 'about'
  end

  get 'video_streams/:id/signed_playback_url', to: 'video_streams#signed_playback_url'
  post 'video_streams/aws_notifications', to: 'aws_notifications#create'

  get '401', :to => 'errors#unauthorized', as: 'unauthorized'
  get '403', :to => 'errors#forbidden', as: 'forbidden'
  get '404', :to => 'errors#not_found', as: 'not_found'

  get 'join/:token', to: 'referrals#join', as: :join
  post 'join/:token', to: 'referrals#join'

  devise_scope :user do
    get 'sign_out', to: 'users/sessions#destroy'
    get 'choose_organization', to: 'users/sessions#choose_organization'
    post 'switch_organization', to: 'users/sessions#switch_organization'
    get 'find_organization', to: 'users/sessions#find_organization'
    post 'find_organization', to: 'users/sessions#find_organization'
    get 'log_in', to: 'users/sessions#new', as: 'new_user_session', override_helpers: true
    get 'sign_up', to: 'registrations#new', as: 'new_user_registration', override_helpers: true
    get 'forgot_password', to: 'passwords#new', as: 'new_user_password', override_helpers: true
    get '/auth/users/establish_handshake', to: 'users/sessions#establish_handshake'
  end
  get 'confirmation', to: 'users/profile#continue', as: :proceed_confirmation
  scope :profile do
    get '', to: 'users/profile#show', as: :user_profile
    get 'edit', to: 'users/profile#edit', as: :edit_user_profile
    patch '', to: 'users/profile#update'
    get 'sign_up/confirmation', to: redirect('/confirmation')
  end
  root 'welcome#index'

  get 'about', to: 'welcome#about'
  get 'careers', to: 'welcome#jobs', as: 'jobs'
  get 'contact', to: 'welcome#contact'
  get 'tos', to: 'welcome#tos'
  get 'privacy', to: 'welcome#privacy'
  get 'ferpa', to: 'welcome#ferpa'
  get 'partners', to: 'welcome#partners'
  get 'eula', to: 'welcome#eula'

  get '/users/groups/:group_id/score', to: 'users#score'
  get 'users/:user_id/user_profile', to: 'users#user_profile'

  get 'developer',                to: 'developers#dev_redir'
  get 'developers',               to: 'developers#index',        as: :dev_home
  get 'developers/manage',        to: 'clients#manage',          as: :dev_manage
  get 'developers/features',      to: 'developers#features',     as: :dev_features
  get 'developers/docs',          to: 'developers#docs',         as: :dev_docs
  get 'developers/invitation',    to: 'developers#invitation',   as: :dev_invitation
  get 'developers/invite',        to: 'developers#invite',       as: :dev_invite
  get 'developers/join/:token',   to: 'developers#join',         as: :dev_join
  post 'developers/admin_create', to: 'developers#admin_create', as: :dev_admin_create
  scope '/developers' do
    resources :background_jobs, only: [:index] do
      member do
        post 'reenqueue', to: 'background_jobs#reenqueue'
      end
    end
  end

  get 'dashboard_stream', to: 'cards#dashboard_stream'
  resources :posts, except: [:new]
  resources :groups, only: [] do
    resources :activity_records, only: [:create]
    resources :notifications, only: [:index]
    resources :events do
      member do
        get 'watch', to: 'events#watch'
      end
    end
    resources :posts, except: [:new] do
      get :filters, on: :collection

      resources :reports, only: [:create]
      get 'reports/stats', to: 'reports#stats'
    end

    member do
      get :preferences
      put :change_preference
      resources :private_groups, only: [:index, :create] do
        collection do
          get :search
          get :enrolled_groups
          get :open_groups
        end
      end
    end

    member do
      resources :users, only: [:index]
    end

    resources :users, only: [] do
      member do
        get 'stats' #show stats for the user belonging to this group
      end
    end

    resources :streams, only: [:index]
  end

  resources :private_groups, except: [:index, :create, :search] do
    member do
      get 'users'
      post 'add_user'
      delete 'remove_user'
      post 'ban_user'
      delete 'unban_user'
    end
  end

  post 'groups/:group_id/posts/:id/restore', to: 'posts#restore'
  get '/groups/:id/stats', to: 'groups#stats'
  get '/groups/:id/right_rail_stats', to: 'groups#right_rail_stats'
  get '/groups/:id/contexts', to: 'groups#contexts'
  get '/groups/:id/topic_stats', to: 'groups#topic_stats'
  post '/groups/upload_s3_urls', to: 'groups#upload_s3_urls'
  get '/groups/channels', to: 'groups#channels'
  get '/groups/forum_channels', to: 'groups#forum_channels'

  get 'course_offerings/:client_resource_id/posts', to: 'posts#index'

  get '/forum_data', to: 'groups#forum_data'
  get '/addon_stats', to: 'groups#addon_stats'
  post '/add_user', to: 'groups#add_user'
  post '/remove_user', to: 'groups#remove_user'
  post '/close_group', to: 'groups#close'
  post '/sync_course_data', to: 'groups#sync_course_data'
  get '/users/:id/org_details', to: 'groups#user_org_details'
  get '/verify_badge/:identifier', to: 'users#verify_badge'

  get 'current_user', to: 'users#current'
  resources :users, only: [:update] do
    member do
      get 'addable_private_groups'
    end

  end

  resources :posts, only: [:destroy, :show] do
    resources :comments, except: [:new] do
      resources :reports, only: [:create]
      get 'reports/stats', to: 'reports#stats'
    end
    resources :votes, only: [:create]
    delete 'votes', to: 'votes#destroy'
    resources :approvals, only: [:create]
    delete 'approvals', to: 'approvals#destroy'
    resources :reports, only: [:create]
    get 'reports/stats', to: 'reports#stats'
    post 'read', to: 'post_reads#create'
    member do
      post 'pin'
      post 'restore'
      post 'convert_to_card'
    end
  end

  resources :comments, only: [:destroy] do
    resources :comments, only: [:index, :show, :create, :update, :destroy]
    resources :votes, only: [:create]
    delete 'votes', to: 'votes#destroy'
    resources :approvals, only: [:create]
    delete 'approvals', to: 'approvals#destroy'
    resources :reports, only: [:create]
    get 'reports/stats', to: 'reports#stats'
    member do
      post 'restore'
    end
  end

  resources :events, only: [] do
    resources :events_users, only: [:create, :update]
    resources :comments, except: [:new] do
      resources :reports, only: [:create]
      get 'reports/stats', to: 'reports#stats'
    end
    resources :votes, only: [:create]
    delete 'votes', to: 'votes#destroy'
    resources :approvals, only: [:create]
    delete 'approvals', to: 'approvals#destroy'
    resources :reports, only: [:create]
    get 'reports/stats', to: 'reports#stats'
    post 'read', to: 'post_reads#create'
  end

  post 'events/:event_id/comments/:id/restore', to: 'comments#restore'
  get 'groups/:group_id/plot/events', to: 'events#plot'
  get 'groups/:group_id/webex_enabled/events', to: 'events#webex_enabled'
  post 'posts/:post_id/comments/:id/restore', to: 'comments#restore'

  resources :clients, only: [:index, :show, :new, :create, :destroy, :update] do
    resources :groups, only: [:index, :update] do
      member do
        post 'clear_posts'
        get 'data_dump'
      end
    end
  end

  resources :channels, only: [] do
    resources :posts, only: [:index, :create, :update, :destroy]
  end

  resources :channels, path: '/manage/channels', only: [:index]

  get '/manage/globalinfluencers', to: 'influencers#show'
  post '/manage/addinfluencers', to: 'influencers#create'
  patch '/manage/updateinfluencersvisibility', to: 'influencers#update_visibility'
  delete '/manage/removeinfluencers', to: 'influencers#destroy'

  get 'home(/:tab)', to: 'organizations#show', as: :organization_home
  get 'organizations/host_name_check', to: 'organizations#host_name_check', as: :org_host_name_check
  post 'organizations/add_user', to: 'organizations#add_user', as: :org_add_user

  resources :organizations, only: [:new, :create]

  get 'ui/qa', to: 'ui#qa'
  get 'ui/events', to: 'ui#events'
  get 'ui/cards', to: 'ui#cards'
  get 'ui/qa_v1', to: 'ui#qa_v1'

  scope module: 'api' do
    resources :cards, path: 'manage/insights', as: 'insights_manage', except: %i[show new]
    get 'create', to: 'cards#new', as: 'new_insights_manage'
  end

  get 'insights/:id/visit', to: 'insights#visit', as: :visit_insight
  get 'api/insights/:id/visit_url', to: 'insights#visit_url'

  post 'lti/forum/v1', to: 'lti#forum_v1'
  post 'lti/events', to: 'lti#events'

  get 'unsubscribe', to: 'follows#unsubscribe'

  get 'preferences', to: 'user_preferences#set_from_token'

  resources :user_preferences, only: [:index] do
    collection do
      patch :update #special route to update by key name rather than by id
      put :update #special route to update by key name rather than by id
    end
  end

  post 'file_resources', to: 'file_resources#create'
  post 'file_resources/v1', to: 'file_resources#create_v1'
  get 'file_resources/:id', to: 'file_resources#show'

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  skip_filter :authenticate_user!
  layout (Settings.features.layout_v4 ? 'application_v4' : 'application_v2')

  def action_missing(m, *args, &block)
    unknown_route
  end

  def index
    if current_org.id == Organization.default_org&.id
      response_body_from_corp = Rails.cache.fetch('home-page-from-corp', expires_in: 1.minutes) do
        conn = Faraday.new(:url => Settings.edcast_wordpress_url )
        response = conn.get '/corp/'
        response.body
      end
      render inline: response_body_from_corp, layout: false and return
    else
      redirect_to new_user_session_path({from_root: true}), status: :moved_permanently and return
    end
  end

  def about

  end

  def jobs

  end

  def contact

  end

  def tos

  end

  def privacy

  end

  def ferpa

  end
  def partners

  end
  def eula

  end

end

app/views/welcome/_channels.html.slim
.row
  .small-12.columns
    .section-title
      h3.text-center Start Exploring The EdCast Knowledge Channels

.row
  .small-12.columns
    ul.small-block-grid-2.medium-block-grid-4.large-block-grid-5.circles-list
      - channels.each do |channel|
        li
          div.circle.center data-link=learn_path(channel) style="background-image: url('#{profile_photo(channel)}');"
            .circle-name = channel.label.titlecase

- content_for :js do
  javascript:
    $('.circle').click(function(){
      window.location.href = $(this).attr('data-link');
    });

app/views/welcome/_marketing.html.slim
// Marketing Section
div style="background-color: #0B9FD8; padding: 4rem 0;"
  .row
    .small-12.columns
      h2.white-font.text-center style="margin-bottom: 3rem;" Drive Knowledge-Sharing Across Teams & Enterprise!
  .row
    .small-12.medium-4.columns.text-center
      = image_tag('destiny_home_graphic.png')
    .small-12.medium-8.columns
      p.white-font Teams can create a private knowledge-sharing network to empower employees, partners and customers with innovative bite-size informal and formal content.  The network provides daily personalized feed of  best-in-class content from the web, subject matter experts/ influencers, team members posts  and livestreams.  Leaders can create teams to share insights, assign pathways for micro learning, and drive deep engagement with internal and external communities of practice.

app/views/welcome/_partners.html.slim
- content_for :head
  link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.5.0/slick.css"
  link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.5.0/slick-theme.css"

// Partners Section
.row
  .small-12.columns
    h3.text-center Our Partners
    br
    br
    .partners-slick
      .bg-white.slick-item.iron-border
        = image_tag asset_path('SDSN.png'), alt: 'Sustainable Development Solutions Network'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('MSU.png'), alt: 'Michigan State University'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('open-education-consortium.png'), alt: 'Open Education Consortium'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('salesforce.png'), alt: 'Salesforce'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('oed.png'), alt: 'Open Online Education'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('cceg-logo.jpeg'), alt: 'Citizenship Enterprise and Governance'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('curtin-university.png'), alt: 'Curtin University'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('unnamed.png'), alt: 'Sama Source'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('academe.png'), alt: 'AcadeMe'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('african-virtual-university.png'), alt: 'African Virtual University'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('EDUONIX_LOGO.png'), alt: 'Eduonix'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('Picture2.jpg'), alt: 'Queensland University Of Technology'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('fame-food-allergy_0.png'), alt: 'Fame Food Allergy Management Europe'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('security-learner.png'), alt: 'Security Learner'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('edx-openedx.png'), alt: 'Open EdX'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('vlsi.png'), alt: 'VLSI'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('Picture1.png'), alt: 'SLATE'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('Our-Partners-36_0.png'), alt: 'Start X'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('wcet-logo.png'), alt: 'WCET'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('Picture9_1.png'), alt: 'Indraprastha Institute Of Information Technology'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('Picture20.png'), alt: 'Manipal Global Education Services'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('graduateInstitute.png'), alt: 'The Graduate Institute'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('hindujaGlobalSolution.png'), alt: 'Hinduja Global Solutions'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('ims-global-learning.png'), alt: 'IMS Global Learning Consortium'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('tie-silicon-valley.png'), alt: 'TIE Silicon Valley'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('Picture15.png'), alt: 'New Schools'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('university-of-botswana.png'), alt: 'University Of Botswana'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('IIT-bombay-logo.png'), alt: 'IIT Bombay'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('Tusk-Academy_2.png'), alt: 'Tusk Academy'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('National-university-of-Rwanda.png'), alt: 'National University Of Rwanda'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('recte-sapere-fons.png'), alt: 'Recte Sapere Fons'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('ucd-University.png'), alt: 'UCD University'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('Bimtech-birla-institute-of-management-technology.png'), alt: 'Bimtech Birla Institute'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('LUX-MEA-LEX-university.png'), alt: 'LUX MEA LEX University'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('iitgn-logo1.jpeg'), alt: 'IIT Gandhinagar'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('Trinity-college-dublin.png'), alt: 'Trinity College Dublin'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('coderjoints.png'), alt: 'Codersjoint'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('bchlogomotto_primary_72dpi.jpeg'), alt: 'Boston Childrens Hospital'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('jainuniversity.jpg'), alt: 'Jain University'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('gifr_logo1.jpeg'), alt: 'Global Institute of Forensic Research'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('Logo_IF.png'), alt: 'Instituto Fonte'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('UPenn_logo_(1).png'), alt: 'Perelman School of Medicine'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('emc_tab_page_head.png'), alt: 'EMC Corporation'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('gems_education.png'), alt: 'GEMS Education'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('Keiretsu_Forum_Academy_logo_2.png'), alt: 'Keiretsu Forum Academy'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('mavericks_logo.png'), alt: 'Mavericks Civilian Space Foundation'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('ICRISAT.jpg'), alt: 'ICRISAT'

      .bg-white.slick-item.iron-border
        = image_tag asset_path('cerego.jpg'), alt: 'Cerego'  

- content_for :js
  script type="text/javascript" src="//cdn.jsdelivr.net/jquery.slick/1.5.0/slick.min.js"

  javascript:
    $('.partners-slick').slick({
      slidesToShow: 4,
      slidesToScroll: 4,
      arrows: true,
      dots: true,

      responsive: [
        {
          breakpoint: 1020,
          settings: {
            slidesToShow: 3,
            slidesToScroll: 3,
            infinite: true,
            dots: true
          }
        },
        {
          breakpoint: 650,
          settings: {
            slidesToShow: 2,
            slidesToScroll: 2,
            infinite: true,
            dots: true
          }
        },
        {
          breakpoint: 400,
          settings: {
            slidesToShow: 1,
            slidesToScroll: 1,
            infinite: true,
            dots: true
          }
        }
      ]
    });

app/views/welcome/contact.html.slim
div.bgk style="background-image: url('/assets/contact_us_new.jpg');"
  .row
    .small-12.columns.small-centered.text-center
      h1.white-font Contact Us
br 		  		 
.row


  .small-12.columns.medium-6.columns
    h6
      strong EdCast Inc.

    p
      |  1901 Old Middlefield Way, Suite 21
      br
      |   Mountain View, CA 94043 USA
      br
      |	Telephone: +1 844-8-EDCAST (+1 844-833-2278)
      br
      |	Fax: +1 650-327-4410

    h6
      strong General Inquiries

    p
      | If you have any questions or comments please contact us at&nbsp;
      a href="mailto:info@edcast.com" info@edcast.com.

    h6
      strong Sales

    p Call Sales anytime at +1 844-8-EDCAST (844-833-2278) and an EdCast Sales Representative will get back to you.

  .small-12.columns.medium-6.columns#map-canvas
br			

.row
  .small-12.columns.medium-4.large-4
    h6
      strong Support

    p
      | For any support matters, please visit our&nbsp;
      a href="http://www.edcast.com/corp/faqs" target="_blank" FAQ's
      |  section. In addition, you are always welcome to contact us at&nbsp;
      a href="mailto:support@edcast.com" support@edcast.com

  .small-12.columns.medium-4.large-4
    h6
      strong Press

    p
      | Please visit our&nbsp;
      a href="http://www.edcast.com/corp/press" target="_blank" Press
      |   section for more information.
      br
      | For general corporate press inquiries, please contact us at&nbsp;

      a href="mailto:press@edcast.com" press@edcast.com

      br
      | For advertising inquiries, please visit our&nbsp;
      a href="http://www.edcast.com/corp/media-kit" target="_blank" Media Kit
      |  section.

  .small-12.columns.medium-4.large-4
    h6
      strong Careers

    p
      | Looking for employment opportunities?
      br
      | Please visit our&nbsp;
      = link_to "Careers", jobs_path, target: '_blank'
      |  section or send your inquiry to&nbsp;
      a href="mailto:careers@edcast.com" careers@edcast.com



- content_for :js do
  script src="https://maps.googleapis.com/maps/api/js?v=3.16"

  javascript:
    function initialize() {

      var mapCanvas = document.getElementById('map-canvas');
      var mapOptions = {
        center: new google.maps.LatLng(37.413644, -122.087082),
        zoom: 17,
        mapTypeId: google.maps.MapTypeId.ROADMAP
      }
      var map = new google.maps.Map(mapCanvas, mapOptions);

      var marker = new google.maps.Marker({
        position: new google.maps.LatLng(37.413644, -122.087082),
        title: 'EdCast Inc.',
        map: map

      });

      var infowindow = new google.maps.InfoWindow({
          content: "<h5><strong>EdCast Inc.</strong></h5><p>1901 Old Middlefield Way #21, Mountain View, CA 94043, United States</p>",
          maxWidth: 300,
          disableAutoPan: true
      });

      google.maps.event.addListener(marker, 'click', function() {
        infowindow.open(map,marker);
      });
      infowindow.open(map,marker);

    }

    google.maps.event.addDomListener(window, 'load', initialize);

app/views/welcome/privacy.html.slim
// Top Banner Section
div.bgk style="background-image: url('/assets/section-bgk-2.jpg');"
  .row
    .small-12.columns.small-centered.text-center
      h1.white-font Privacy Policy

.row
  .small-12.columns
    .section-title
    p
      | EdCast, Incorporated ("EDC") understands the importance of protecting the privacy of all information that we collect by users of our websites, subscribers to our newsletters and other information services and customers of our products and services. This Privacy Policy outlines our use and disclosure of the personal information collected by or submitted to EDC on all EDC-owned websites, including: EdCast.com, Course-Master.com, "university name".coursemaster.net, CourseMaster.net, Coursemaster.me, enterprise.CourseMaster.com or third party sites that use EDC applications like EDC's social collaboration learning app.

    h3.pink-font What information do we collect?

    p
      | We collect information from you when you register on our site, place an order, subscribe to our newsletter, file a support request, download a product, sign up for a trial, respond to a survey, send us an inquiry, post to our forums, watch a webcast or fill out a form. EDC also collects personal information by telephone, mail and at conventions, seminars, trade shows and exhibitions. The information collected may include your: name, e-mail address, mailing address, phone number, company name, IP address, username and password or credit card information. For EDC products and services that require payment, such as purchasing a license, subscribing to a product, or registering for a course, EDC collects credit card information, which is used for billing purposes by EDC or EDC's agent only. It is not otherwise shared with any third parties. EDC also collects non-personally-identifying information from website visitors, such as browser type, language preference, referring site, and other information typically made available by browsers and servers in order to better understand how visitors use our website.

    h3.pink-font What do we use your information for?

    p
      | Any of the information we collect from you may be used to manage accounts, register visitors in programs, answer questions, improve our website, improve our customer service, and to process transactions. Your information, whether public or private, will not be sold, exchanged, transferred, or given to any other company for any reason whatsoever, without your consent, other than for the express purpose of delivering the purchased product or service requested, to administer a contest, promotion, survey or other site feature, to send email notifications on EDC's behalf or to comply with court orders and regulations. EDC reserves the right to share personal information consequent to a merger, acquisition, or divestiture of our business. The email address you provide for order processing may be used to send you information and updates pertaining to your order, in addition to receiving occasional company news, updates, related product or service information, etc. If at any time you would like to unsubscribe from receiving future emails, we include detailed unsubscribe instructions at the bottom of each email. You may also contact us via email, phone or mail at the addresses provided at the end of this document to request that we remove you from our email list.

    h3.pink-font How do we protect your information?

    p
      | We implement a variety of security measures to maintain the safety of your personal information when you place an order. We offer the use of a secure server. All supplied sensitive/credit information is transmitted in encrypted format and then sent into our payment processing engine only to be accessible by those authorized with special access rights to such systems, and are required to keep the information confidential. After a transaction, your private information (credit cards, social security numbers, financials, etc.) may be kept on file solely for the purpose of processing your recurring subscription payments until such a subscription is cancelled.

    h3.pink-font Do we use cookies?

    p
      | Yes. Cookies are small files that a site or its service provider transfers to your computer's hard drive through your Web browser (if you allow it) that enables the site's or service provider's systems to recognize your browser and capture and remember certain information We use cookies to help us understand and save your preferences for future visits, keep track of advertisements and compile aggregate data about site traffic and site interaction so that we can offer better site experiences and tools in the future. We may contract with third-party service providers to assist us in better understanding our site visitors. These service providers are not permitted to use the information collected on our behalf except to help us conduct and improve our business. If you prefer, you can choose to have your computer warn you each time a cookie is being sent, or you can choose to turn off all cookies via your browser settings. Like most websites, if you turn your cookies off, some of our services may not function properly. However, you can still place orders by contacting customer service.

    h3.pink-font Do we disclose any information to outside parties?

    p
      | We do not sell, trade, or otherwise transfer to outside parties your personally identifiable information. This does not include trusted third parties who assist us in operating our website, conducting our business, or servicing you, so long as those parties agree to keep this information confidential. We may make non-personally-identifiable information available to third parties in aggregate form only for purposes such as providing advertising targeted towards visitors to EDC websites, users of EDC or to show general usage trends. We may also release your information when we believe release is appropriate to comply with the law, enforce our site policies, or protect ours or others rights, property, or safety.

    h3.pink-font Third party links

    p
      | Occasionally, at our discretion, we may include or offer third party products or services on our website. These third party sites have separate and independent privacy policies. We therefore have no responsibility or liability for the content and activities of these linked sites. Nonetheless, we seek to protect the integrity of our site and welcome any feedback about these sites.

    h3.pink-font California Online Privacy Protection Act Compliance

    p
      | Because we value your privacy we have taken the necessary precautions to be in compliance with the California Online Privacy Protection Act. We therefore will not distribute your personal information to outside parties without your consent.

    h3.pink-font Children's Online Privacy Protection Act Compliance

    p
      | We are in compliance with the requirements of COPPA (Children's Online Privacy Protection Act). Our website, products and services are all directed to people who are at least 13 years old or older.

    h3.pink-font Terms and Conditions

    p
      | Please also visit our Terms and Conditions section establishing the use, disclaimers, and limitations of liability governing the use of our website at&nbsp;

      = link_to 'Terms of Service', tos_path, target: '_blank'
      | .

    h3.pink-font Your Consent

    p
      | By using our site, you consent to our website's privacy policy.

    h3.pink-font Changes to our Privacy Policy

    p
      | If we decide to change our privacy policy, we will post those changes on this page. This policy was last modified on August 16, 2014.

    h3.pink-font Contacting Us

    p
      | If there are any questions regarding this privacy policy you may contact us using the information below.

    p
      | EdCast Incorporated
      br
      | 1901 Old Middlefield Way, Suite 21
      br
      | Mountain View, CA 94043 USA
      br
      a href="mailto:info@edcast.com" info@edcast.com
      br
      | +1.844.8.EDCAST (+1.844.833.2278)