config/routes.rb
require 'sidekiq/web'
class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

Edcast::Application.routes.draw do

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post "/graphql", to: "graphql#execute"
  use_doorkeeper do
    # it accepts :authorizations, :tokens, :applications and :authorized_applications
    skip_controllers :applications, :authorized_applications
  end

  ## WEBAPP ENDPOINTS

  devise_for :users, path_prefix: 'auth', controllers: { sessions: "users/sessions", confirmations: 'confirmations', registrations: 'registrations', passwords: 'passwords' }
  apipie

  controller 'user_pages' do
    get 'settings(/:tab)', action: 'settings', as: 'settings'
    get 'notifications'
    get 'channels(/:tab)', action: 'channels', as: :user_channels_page
    put 'edit_settings'
    patch 'handle'
    get '/users/:handle', to: 'user_pages#check_handle', as: 'check_handle'
    # get 'about'
  end

  get 'video_streams/:id/signed_playback_url', to: 'video_streams#signed_playback_url'
  post 'video_streams/aws_notifications', to: 'aws_notifications#create'

  get '401', :to => 'errors#unauthorized', as: 'unauthorized'
  get '403', :to => 'errors#forbidden', as: 'forbidden'
  get '404', :to => 'errors#not_found', as: 'not_found'

  get 'join/:token', to: 'referrals#join', as: :join
  post 'join/:token', to: 'referrals#join'

  devise_scope :user do
    get 'sign_out', to: 'users/sessions#destroy'
    get 'choose_organization', to: 'users/sessions#choose_organization'
    post 'switch_organization', to: 'users/sessions#switch_organization'
    get 'find_organization', to: 'users/sessions#find_organization'
    post 'find_organization', to: 'users/sessions#find_organization'
    get 'log_in', to: 'users/sessions#new', as: 'new_user_session', override_helpers: true
    get 'sign_up', to: 'registrations#new', as: 'new_user_registration', override_helpers: true
    get 'forgot_password', to: 'passwords#new', as: 'new_user_password', override_helpers: true
    get '/auth/users/establish_handshake', to: 'users/sessions#establish_handshake'
  end
  get 'confirmation', to: 'users/profile#continue', as: :proceed_confirmation
  scope :profile do
    get '', to: 'users/profile#show', as: :user_profile
    get 'edit', to: 'users/profile#edit', as: :edit_user_profile
    patch '', to: 'users/profile#update'
    get 'sign_up/confirmation', to: redirect('/confirmation')
  end
  root 'welcome#index'

  get 'about', to: 'welcome#about'
  get 'careers', to: 'welcome#jobs', as: 'jobs'
  get 'contact', to: 'welcome#contact'
  get 'tos', to: 'welcome#tos'
  get 'privacy', to: 'welcome#privacy'
  get 'ferpa', to: 'welcome#ferpa'
  get 'partners', to: 'welcome#partners'
  get 'eula', to: 'welcome#eula'

  get '/users/groups/:group_id/score', to: 'users#score'
  get 'users/:user_id/user_profile', to: 'users#user_profile'

  get 'developer',                to: 'developers#dev_redir'
  get 'developers',               to: 'developers#index',        as: :dev_home
  get 'developers/manage',        to: 'clients#manage',          as: :dev_manage
  get 'developers/features',      to: 'developers#features',     as: :dev_features
  get 'developers/docs',          to: 'developers#docs',         as: :dev_docs
  get 'developers/invitation',    to: 'developers#invitation',   as: :dev_invitation
  get 'developers/invite',        to: 'developers#invite',       as: :dev_invite
  get 'developers/join/:token',   to: 'developers#join',         as: :dev_join
  post 'developers/admin_create', to: 'developers#admin_create', as: :dev_admin_create
  scope '/developers' do
    resources :background_jobs, only: [:index] do
      member do
        post 'reenqueue', to: 'background_jobs#reenqueue'
      end
    end
  end

  get 'dashboard_stream', to: 'cards#dashboard_stream'
  resources :posts, except: [:new]
  resources :groups, only: [] do
    resources :activity_records, only: [:create]
    resources :notifications, only: [:index]
    resources :events do
      member do
        get 'watch', to: 'events#watch'
      end
    end
    resources :posts, except: [:new] do
      get :filters, on: :collection

      resources :reports, only: [:create]
      get 'reports/stats', to: 'reports#stats'
    end

    member do
      get :preferences
      put :change_preference
      resources :private_groups, only: [:index, :create] do
        collection do
          get :search
          get :enrolled_groups
          get :open_groups
        end
      end
    end

    member do
      resources :users, only: [:index]
    end

    resources :users, only: [] do
      member do
        get 'stats' #show stats for the user belonging to this group
      end
    end

    resources :streams, only: [:index]
  end

  resources :private_groups, except: [:index, :create, :search] do
    member do
      get 'users'
      post 'add_user'
      delete 'remove_user'
      post 'ban_user'
      delete 'unban_user'
    end
  end

  post 'groups/:group_id/posts/:id/restore', to: 'posts#restore'
  get '/groups/:id/stats', to: 'groups#stats'
  get '/groups/:id/right_rail_stats', to: 'groups#right_rail_stats'
  get '/groups/:id/contexts', to: 'groups#contexts'
  get '/groups/:id/topic_stats', to: 'groups#topic_stats'
  post '/groups/upload_s3_urls', to: 'groups#upload_s3_urls'
  get '/groups/channels', to: 'groups#channels'
  get '/groups/forum_channels', to: 'groups#forum_channels'

  get 'course_offerings/:client_resource_id/posts', to: 'posts#index'

  get '/forum_data', to: 'groups#forum_data'
  get '/addon_stats', to: 'groups#addon_stats'
  post '/add_user', to: 'groups#add_user'
  post '/remove_user', to: 'groups#remove_user'
  post '/close_group', to: 'groups#close'
  post '/sync_course_data', to: 'groups#sync_course_data'
  get '/users/:id/org_details', to: 'groups#user_org_details'
  get '/verify_badge/:identifier', to: 'users#verify_badge'

  get 'current_user', to: 'users#current'
  resources :users, only: [:update] do
    member do
      get 'addable_private_groups'
    end

  end

  resources :posts, only: [:destroy, :show] do
    resources :comments, except: [:new] do
      resources :reports, only: [:create]
      get 'reports/stats', to: 'reports#stats'
    end
    resources :votes, only: [:create]
    delete 'votes', to: 'votes#destroy'
    resources :approvals, only: [:create]
    delete 'approvals', to: 'approvals#destroy'
    resources :reports, only: [:create]
    get 'reports/stats', to: 'reports#stats'
    post 'read', to: 'post_reads#create'
    member do
      post 'pin'
      post 'restore'
      post 'convert_to_card'
    end
  end

  resources :comments, only: [:destroy] do
    resources :comments, only: [:index, :show, :create, :update, :destroy]
    resources :votes, only: [:create]
    delete 'votes', to: 'votes#destroy'
    resources :approvals, only: [:create]
    delete 'approvals', to: 'approvals#destroy'
    resources :reports, only: [:create]
    get 'reports/stats', to: 'reports#stats'
    member do
      post 'restore'
    end
  end

  resources :events, only: [] do
    resources :events_users, only: [:create, :update]
    resources :comments, except: [:new] do
      resources :reports, only: [:create]
      get 'reports/stats', to: 'reports#stats'
    end
    resources :votes, only: [:create]
    delete 'votes', to: 'votes#destroy'
    resources :approvals, only: [:create]
    delete 'approvals', to: 'approvals#destroy'
    resources :reports, only: [:create]
    get 'reports/stats', to: 'reports#stats'
    post 'read', to: 'post_reads#create'
  end

  post 'events/:event_id/comments/:id/restore', to: 'comments#restore'
  get 'groups/:group_id/plot/events', to: 'events#plot'
  get 'groups/:group_id/webex_enabled/events', to: 'events#webex_enabled'
  post 'posts/:post_id/comments/:id/restore', to: 'comments#restore'

  resources :clients, only: [:index, :show, :new, :create, :destroy, :update] do
    resources :groups, only: [:index, :update] do
      member do
        post 'clear_posts'
        get 'data_dump'
      end
    end
  end

  resources :channels, only: [] do
    resources :posts, only: [:index, :create, :update, :destroy]
  end

  resources :channels, path: '/manage/channels', only: [:index]

  get '/manage/globalinfluencers', to: 'influencers#show'
  post '/manage/addinfluencers', to: 'influencers#create'
  patch '/manage/updateinfluencersvisibility', to: 'influencers#update_visibility'
  delete '/manage/removeinfluencers', to: 'influencers#destroy'

  get 'home(/:tab)', to: 'organizations#show', as: :organization_home
  get 'organizations/host_name_check', to: 'organizations#host_name_check', as: :org_host_name_check
  post 'organizations/add_user', to: 'organizations#add_user', as: :org_add_user

  resources :organizations, only: [:new, :create]

  get 'ui/qa', to: 'ui#qa'
  get 'ui/events', to: 'ui#events'
  get 'ui/cards', to: 'ui#cards'
  get 'ui/qa_v1', to: 'ui#qa_v1'

  scope module: 'api' do
    resources :cards, path: 'manage/insights', as: 'insights_manage', except: %i[show new]
    get 'create', to: 'cards#new', as: 'new_insights_manage'
  end

  get 'insights/:id/visit', to: 'insights#visit', as: :visit_insight
  get 'api/insights/:id/visit_url', to: 'insights#visit_url'

  post 'lti/forum/v1', to: 'lti#forum_v1'
  post 'lti/events', to: 'lti#events'

  get 'unsubscribe', to: 'follows#unsubscribe'

  get 'preferences', to: 'user_preferences#set_from_token'

  resources :user_preferences, only: [:index] do
    collection do
      patch :update #special route to update by key name rather than by id
      put :update #special route to update by key name rather than by id
    end
  end

  post 'file_resources', to: 'file_resources#create'
  post 'file_resources/v1', to: 'file_resources#create_v1'
  get 'file_resources/:id', to: 'file_resources#show'

app/models/stream.rb
# == Schema Information
#
# Table name: streams
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  group_id   :integer
#  action     :string(255)
#  item_id    :integer
#  item_type  :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Stream < ActiveRecord::Base
  belongs_to :user
  belongs_to :group

  # Following is the list of supported cases with the corresponding assignments for "item" at the moment:
  # (a) user makes a post/announcement in the forum (item -> post)
  # (b) user makes a comment on a post/announcement/comment (item -> comment)
  # (c) user likes a post/announcement/comment (item -> liked object)
  # (d) user approecs a post/comment (item -> approved object)
  # (e) user joins a private group (item -> private group)
  belongs_to :item, polymorphic: true

  scope :forum_activities, -> { where action: ['commented', 'asked', 'posted'] }

  def snippet
    item.respond_to?(:snippet) ? item.snippet : ''
  end

  def message
    class_name = item.class.name
    item_class_name = class_name == 'Question' ? 'Discussion' : (class_name == "PrivateGroup" ? "Group" : class_name)

    case action
    when 'commented'
      if item.commentable_type == 'Post'
        msg = "commented on discussion"
      else
        msg = "responded to comment"
      end
    when 'liked', 'approved'
      msg = "#{action} the #{item_class_name.humanize.downcase}"
    when 'joined'
      msg = "#{action} #{item_class_name.humanize.downcase.indefinitize}"
    when 'asked'
      msg = "started discussion"
    when 'posted'
      msg = "made #{item_class_name.humanize.downcase.indefinitize}"
    end

  end

  def is_mobile?
    item.respond_to?('is_mobile?') ? item.is_mobile? : false
  end

  def organization
    item.try(:organization)
  end
end

app/controllers/streams_controller.rb
class StreamsController < ApiController

  api :GET, "groups/:group_id/streams", "Get stream of activities from a given group. Returns the newest activity to oldest activity"
  param :group_id, Integer, desc: "The concerned group", required: true
  param :limit, Integer, desc: "page limit", required: false
  param :page, Integer, desc: "page number", required: false
  param :last_fetch_time, Integer, desc: "last fetch time", required: false
  formats ['json']

  def index
    group_id = params.require(:group_id)
    limit    = params[:limit].blank? ? 20 : [params[:limit].to_i, 20].min
    offset   = params[:page].blank? ? 0 : (params[:page].to_i * limit.to_i)

    # make sure it works with blank string
    last_fetch_time = params[:last_fetch_time].blank? ? nil : params[:last_fetch_time]
    streams = Stream.includes(:user, :item).where(group_id: group_id).forum_activities

    if params[:context_id].present?
      post_ids = Post.where(context_id: params[:context_id]).pluck(:id)
      comment_ids = Comment.where(commentable_type: "Post", commentable_id: post_ids).pluck(:id)
      streams = streams.where("(item_type = 'Post' AND item_id IN(?)) OR (item_type = 'Comment' AND item_id IN(?))", post_ids, comment_ids)
    end

    @streams =  last_fetch_time ?
      streams.where('updated_at > ?', DateTime.parse(last_fetch_time)).order!(updated_at: :desc) :
      streams.order!(updated_at: :desc).limit(limit).offset(offset)

    response.headers['X-Last-Fetch-Timestamp'] =
       @streams.first ? @streams.first.updated_at.utc.strftime('%Y-%m-%dT%H:%M:%S.%LZ') : (last_fetch_time || nil)


    # only including the streams
    # whose item(post, comment) do not have hidden = 1
    @streams = @streams.select do |s|
      if !s.item
        false
      # if there is a hidden function in the item i.e it is a commentor a post,
      elsif s.item.respond_to?(:hidden)
        # this returns 1 if it is 0 & vice versa
        not s.item.hidden
      else
        # if the item is not a post or a comment it inserts the stream into the resultset
        true
      end
    end

  end
end

app/views/common/streams/_add_to_pack_stream.html.slim
a.on-hover-actions.add-to-pack data-dropdown="card-packs-dropdown-#{stream.id}-VideoStream" href='#' data-options="align:#{dir}" data-id="#{stream.id}" data-type="VideoStream"
ul.f-dropdown.add-to-pack-dropdown aria-hidden="true" data-dropdown-content="" id="card-packs-dropdown-#{stream.id}-VideoStream"

app/views/common/streams/_inline_live_stream.html.slim
.row
  .small-12.columns
    .section-header
      - unless hide_title
        .section-title Live Stream
    .main-body style="margin: 0 25px;"
      - add_to_pack_stream_enabled = streams_add_to_pack_enabled?
      = react_component('VideoStreamContainer', {'isEmbedded' => true, 'user' => (user.nil? ? nil : ActiveSupport::JSON.decode(render partial: 'users/details', formats: [:json], locals: {user: user, anonymous: nil, include_email: false, include_score_entry: false})), 'recording' => nil, 'viewers' => (viewers.blank? ? [] : []), 'comments' => (comments.blank? ? [] : ActiveSupport::JSON.decode(render template: 'comments/index', formats: [:json], locals: (user.nil? ? {exclude_upvotes: true} : {}).merge({exclude_user_score: true, exclude_flag: true, exclude_approvals: true}))), 'videoStream' => ({'shareUrl' => video_stream_url(id: video_stream.id)}.merge(ActiveSupport::JSON.decode(render partial: 'api/video_streams/details', formats: [:json], locals: {video_stream: video_stream, user: user}))), addToPackEnabled: add_to_pack_stream_enabled, theatreModeEnabled: theatre_mode_enabled?}, {prerender: true})

= render partial: 'common/streams/stream_setup', locals: {user: user, status: 'live'}
- content_for :js do
  javascript:
    var addthis_share = {
      url: "#{video_stream_url(video_stream.id)}",
      title: "#{video_stream.name}"
    };
= render partial: 'common/addthis_widget' if @can_share_on_social_nw

app/views/common/streams/_past_stream.html.slim
li
  div class="video-card past-stream-card" data-href="#{video_stream_path(stream.slug)}" style="background-image: url(#{stream.image || image_url('card_default_image_min.jpg')});"
    .card-overlay
    .card-label Stream
    .card-section
      .card-divider.clearfix
        - if stream.creator.handle.blank?
          img.avatar.avatar-default.circle-white-border.left src="#{stream.creator.photo}"
        - else
          a href="#{public_user_page_path(handle: handle_no_at(stream.creator.handle))}" data-amplitude-trigger='click' data-amplitude-event='view_user' data-amplitude-event-props='{"action" : {"type" : "view"}, "object" : {"class" : "user", "id" : "#{stream.creator.id}"}}'
            img.avatar.avatar-default.circle-white-border.left src="#{stream.creator.photo}"
        .actions-wrapper.clearfix
          .actions.right
            ul
              li.commentCount.white
                = stream.comments_count
              li.likeCount.white
                = stream.votes_count
          .author-name.left
            - if stream.creator.handle.blank?
              = stream.creator.name
            - else
              a.truncate data-amplitude-trigger='click' data-amplitude-event='view_user' data-amplitude-event-props='{"action" : {"type" : "view"}, "object" : {"class" : "user", "id" : "#{stream.creator.id}"}}' href="#{public_user_page_path(handle: handle_no_at(stream.creator.handle))}"
                = stream.creator.name
      .card-content
        h6.title
          = stream.name
      ul.inline-list.tags
        - tags = stream.tags
        - if tags
          - stream.tags.each do |tag|
            li
              a href="#{search_path(q: tag.name)}"
                = tag.name
    a.on-hover-actions.open-card href=video_stream_path(stream.slug)
    - if streams_add_to_pack_enabled? && user_signed_in?
      = render partial: 'common/streams/add_to_pack_stream', locals: {stream: stream, dir: "left"}
- content_for :js
  javascript:
    $(document).on("click", ".past-stream-card", function(e){
      var skip = e.target.classList.contains("add-to-pack") || e.target.classList.contains("add-to-pack-dropdown") || $(e.target).parents(".add-to-pack-dropdown").length
      if(skip) { return; }
      window.location.href = $(this).data("href");
    });

app/views/common/streams/_scheduled_stream.html.slim
li
  .scheduled-stream.clearfix.scheduled-stream-js data-stream-path="#{video_stream_path(stream.slug)}"
    .left.stream-icon style="background-image: url('#{stream.image || image_url('card_default_image_min.jpg')}');"
    .stream-detail.left
      .small-font = stream.creator.name
      - if streams_add_to_pack_enabled? && user_signed_in?
        = render partial: 'common/streams/add_to_pack_stream', locals: {stream: stream, dir: "right"}
      .time-addthis.clearfix
        .left.localize-timestamp.small-font data-timestamp="#{stream.start_time}"
        .right
          .addthisevent title=("Add to Calendar") style=("z-index: 1;")
            span.start.addthisevent-localize-starttime data-timestamp="#{stream.start_time}"
            span.end.addthisevent-localize-starttime data-timestamp="#{stream_end_time(stream)}"
            span.title= "#{stream.name} on EdCast"
            span.description
              | Watch live on the web: #{video_stream_url(stream.slug)}
              br
              | Get the EdCast app to watch it live on your mobile device:
              br
              | Download on iOS - https://itunes.apple.com/app/apple-store/id974833832?pt=100220803&ct=KKWebsiteLink&mt=8
              br
              | Download on Android - https://play.google.com/store/apps/details?id=com.edcast
      .title = stream.name

app/views/common/streams/_search_stream_item.html.slim
li.no-list-style.search-stream-item
  .wrapper
    .row
      .small-12.columns style="padding:0"
        - if stream.creator.present?
          a.left.video-creator-icon href='#{public_user_page_path(handle: handle_no_at(stream.creator.normalized_handle))}' data-amplitude-trigger='click' data-amplitude-event='view_user' data-amplitude-event-props='{"action" : {"type" : "view"}, "object" : {"class" : "user", "id" : "#{stream.creator.id}"}}'
            img.avatar.avatar-default.circle-white-border src="#{stream.creator.photo}"
            - if stream.creator.is_suspended
              img.stream-suspend-icon src="#{asset_url('suspended_user_icon.png')}"
          .left.wrapper
            .stream-creator.detail.left.medium-font
              a.bold.video-insight-link.truncate href='#{public_user_page_path(handle: handle_no_at(stream.creator.normalized_handle))}' data-amplitude-trigger='click' data-amplitude-event='view_user' data-amplitude-event-props='{"action" : {"type" : "view"}, "object" : {"class" : "user", "id" : "#{stream.creator.id}"}}'
                = stream.creator.name
                .mute-font.small-font.stream-handle = stream.creator.normalized_handle
        - if stream.status == "live"
          .right.live-now-button
            .floating-label.pink
              =image_tag asset_path('live_stream.png'), class: 'icon'
              |Live Now!
        - if stream.status == "past"
          .right.live-now-button
            .floating-label.grey
              = image_tag asset_path('paststream_icon.png'), class: 'icon'
              |PAST STREAM
        - if stream.status == "upcoming"
          .right.live-now-button
            .floating-label.grey
              = image_tag asset_path('paststream_icon.png'), class: 'icon'
              |SCHEDULED STREAM

    .row.small-collapse
      .small-5.columns
        a.image-container href='#{video_stream_path(stream.slug)}' data-amplitude-trigger='click' data-amplitude-event='view_stream' data-amplitude-event-props='{"action" : {"type" : "view"}, "object" : {"class" : "livestream", "#{stream.id}"}}'
          .insight-picture style="background: url(#{video_stream_display_image(stream)}) center center no-repeat; background-size: cover; cursor:pointer; height: 150px;"
            = image_tag asset_path('play_button.png'), width: '50', height: '50', class: 'play-link'
      .small-7.columns
        .stream-content
          a.bold.video-insight-link.line-clamp-3 href="#{video_stream_path(stream.slug)}" data-amplitude-trigger='click' data-amplitude-event='view_stream' data-amplitude-event-props='{"action" : {"type" : "view"}, "object" : {"class" : "livestream", "#{stream.id}"}}' = stream.name
          .time-addthis.clearfix
            .mute-font.left.localize-timestamp.medium-font data-timestamp="#{stream.start_time}"
          - if stream.status == "live"
            .live-button
              a.button.hollow.small.watch-button href='#{video_stream_path(stream.slug)}' data-amplitude-trigger='click' data-amplitude-event='view_stream' data-amplitude-event-props='{"action" : {"type" : "view"}, "object" : {"class" : "livestream", "#{stream.id}"}}' Watch Now
          - if stream.status == "upcoming"
            .clearfix
              .left.small-font style="line-height: 40px;" Remind Me:
              .addthisevent title=("Add to Calendar") style=("z-index: 1; border:0;")
                span.start.addthisevent-localize-starttime data-timestamp="#{stream.start_time}" = stream.start_time
                span.end.addthisevent-localize-starttime data-timestamp="#{stream_end_time(stream)}" = stream_end_time(stream)
                span.title= "#{stream.creator.name} on EdCast"
                span.description
                  | Watch live on the web: #{video_stream_path(stream.slug)}
                  br
                  | Get the EdCast app to watch it live on your mobile device:
                  br
                  | Download on iOS - https://itunes.apple.com/app/apple-store/id974833832?pt=100220803&ct=KKWebsiteLink&mt=8
                  br
                  | Download on Android - https://play.google.com/store/apps/details?id=com.edcast
          - if stream.status == "past"
            .button-section
              .small-font style="padding: 0.5rem 0rem;"
              a.button.hollow.small.watch-button href='#{video_stream_path(stream.slug)}' data-amplitude-trigger='click' data-amplitude-event='view_stream' data-amplitude-event-props='{"action" : {"type" : "view"}, "object" : {"class" : "livestream", "#{stream.id}"}}' Watch
    br

app/views/common/streams/_search_streams_list.html.slim
- if local_assigns[:video_streams].present?
  - section_title ||= 'Video Streams'
  - live_streams, upcoming_streams, past_streams = [], [], []
  - video_streams.each do |stream|
    - live_streams.push(stream) if stream.status == 'live'
    - upcoming_streams.push(stream) if stream.status == 'upcoming'
    - past_streams.push(stream) if stream.status == 'past'

- block_grid_class = Settings.features.layout_v4 ? 'small-block-grid-1 cards-list' : 'small-block-grid-1 medium-block-grid-2 large-block-grid-2 cards-list'
#video-streams-list
  - if live_streams.present?
    .section-header
      .section-title Live Streams
      - if local_assigns[:description]
        .section-description #{description}
    ul.search-stream-list
      - live_streams.each do |stream|
        = render partial: 'common/streams/search_stream_item', locals: {stream: stream}
  - if upcoming_streams.present?
    .section-header
      .section-title Scheduled Streams
      - if local_assigns[:description]
        .section-description #{description}
    ul.search-stream-list
      - upcoming_streams.each do |stream|
        = render partial: 'common/streams/search_stream_item', locals: {stream: stream}
  - if past_streams.present?
    .section-header
      .section-title Past Streams
      - if local_assigns[:description]
        .section-description #{description}
    ul.search-stream-list
      - past_streams.each do |stream|
        = render partial: 'common/streams/search_stream_item', locals: {stream: stream}

app/views/common/streams/_stream_setup.html.slim
- content_for :js do
  = javascript_include_tag '//cdn.pubnub.com/pubnub-3.7.1.min.js'
  - if @current_org.present?
    javascript:
      window.cobrands = #{ActiveSupport::JSON.encode(@current_org.fetch_cobrand_configs_with_defaults).html_safe}

  = javascript_include_tag "#{Settings.jwplayer_library_url}"
  javascript:
    var user = #{user.nil? ? 'false' : ActiveSupport::JSON.decode((render partial: 'users/details', formats: ['json'], locals: {user: user, anonymous: nil, include_email: false, include_score_entry: false})).to_json.html_safe};
  - if status == 'live'
    javascript:
      var anonymousUserImage = "#{ActionController::Base.helpers.asset_path('anonymous-user.png')}";
      var pubnub = PUBNUB.init({
        publish_key: #{Settings.pubnub.publish_key.to_json.html_safe},
        subscribe_key: #{Settings.pubnub.subscribe_key.to_json.html_safe},
        ssl: true
      });

app/views/common/streams/_streams_list.html.slim
- if local_assigns[:video_streams].present?
  - section_title ||= 'Streams'
.row
  .small-12.columns
    .section-header
      .section-title = section_title
      - if local_assigns[:description]
        .section-description #{description}
    ul.cards-list style="margin-bottom:0px" class=("#{Settings.features.layout_v4 ? 'small-block-grid-1 medium-block-grid-1 large-block-grid-1' : 'small-block-grid-1 medium-block-grid-2 large-block-grid-3'}")
      - if status == 'upcoming'
        - video_streams.each do |stream|
          = render partial: 'common/streams/scheduled_stream', locals: {stream: stream}
      - elsif status == 'past'
        - video_streams.each do |stream|
          = render partial: 'common/streams/past_stream', locals: {stream: stream}
      - elsif status == 'live'
        - if !@top_live_video_stream.nil?
          = render partial: 'common/streams/inline_live_stream', locals: {video_stream: @top_live_video_stream, user: current_user, hide_title: true, comments: [], viewers: []}
        - else
          - video_streams.each do |stream|
            = render partial: 'common/streams/past_stream', locals: {stream: stream}